# Generated by Django 5.2.14 on 2026-05-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('complaint', models.TextField()),
                ('category', models.CharField(choices=[('Technical', 'Technical'), ('Academic', 'Academic'), ('Hostel', 'Hostel'), ('Other', 'Other')], max_length=50)),
                ('status', models.CharField(default='Pending', max_length=20)),
            ],
        ),
    ]
