# Generated by Django 5.2.14 on 2026-06-01 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),

        migrations.AddField(
            model_name='grievance',
            name='latitude',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='grievance',
            name='longitude',
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True
            ),
        ),

        migrations.AddField(
            model_name='grievance',
            name='photo',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='complaint_photos/'
            ),
        ),

        migrations.AddField(
            model_name='grievance',
            name='priority',
            field=models.CharField(
                choices=[
                    ('Low', 'Low'),
                    ('Medium', 'Medium'),
                    ('High', 'High')
                ],
                default='Low',
                max_length=20
            ),
        ),

        migrations.AddField(
            model_name='grievance',
            name='tracking_id',
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True
            ),
        ),

        migrations.AddField(
            model_name='grievance',
            name='user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),

        migrations.AlterField(
            model_name='grievance',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('In Progress', 'In Progress'),
                    ('Resolved', 'Resolved'),
                    ('Rejected', 'Rejected')
                ],
                default='Pending',
                max_length=20
            ),
        ),
    ]