# Generated by Django 5.2.14 on 2026-06-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0002_grievance_created_at_grievance_tracking_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='grievance',
            name='latitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='longitude',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grievance',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='complaint_photos/'),
        ),
    ]
