# Generated by Django 5.2.14 on 2026-06-01 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0002_grievance_created_at_grievance_language_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='language',
        ),
        migrations.RemoveField(
            model_name='grievance',
            name='translated_complaint',
        ),
    ]
