# Generated by Django 5.2.14 on 2026-06-01 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0004_grievance_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievance',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
